### ISSUE TITLE
Optimize DISTINCT + ORDER BY

### ISSUE THREAD

**Issue by MrNeocore** [apache/incubator-pinot#7060] opened 2021-06-15 19:36 UTC
Following Slack discussion : https://apache-pinot.slack.com/archives/C011C9JHN7R/p1623782718117700

**Context**
Documents: 100M
Segments: 90

**Query**
Getting DISTINCT values for a low cardinality column (45 distinct STRINGs)

Query `select DISTINCT(kpi) from kpis` takes ~10ms
While `select DISTINCT(kpi) from kpis ORDER BY kpi` takes more than **300ms**

Please have a look at the discussion by @mayankshriv and @kishoreg for more technical details

**Comment by atris** [comment] 2021-06-28 15:52
I would like to take this up please. Please. assign this to me

**Comment by kishoreg** [comment] 2021-06-28 16:00
Done

**Comment by atris** [comment] 2021-06-28 16:19
Thanks!

**Comment by atris** [comment] 2021-06-30 11:02
So I investigated this and noted that in case there is no ORDER BY present, there is a possibility that we will early terminate during a DISTINCT operation. However, in case of ORDER BY being present, DistinctCombineOperator will not allow early termination, thus forcing all segments to be processed.

I do not see how we can avoid this, since ORDER BY will have to ensure that the results are ordered globally, irrespective of the limit.

I think a better way would be to support DISTINCT operation to work on top of dictionary, in case the conditions are matched. I will work on the PR

**Comment by mayankshriv** [comment] 2021-06-30 17:32
IIRC, the result returned in both cases was the same, so early terminate may not apply for this case, so I think something else is going on. @wuwenw @Jackie-Jiang can you take a look on the latency difference.

@atris Yes, it would be great to add dictionary based distinct support if you are up for it.

**Comment by mayankshriv** [comment] 2021-06-30 17:57
Chatted with @atris, there's indeed a bailout that stops scanning records after we hit the record limit during the combine phase of distinct operator. It is just a fluke that the results matched even though we didn't scan all records. For other use cases, early bailout in case of no order-by and small limit may result in incorrect results.

**Comment by mayankshriv** [comment] 2021-06-30 17:58
@MrNeocore As an experiment, can you try a really large value of limit in your query? I think the first query performance will also degrade.

**Comment by MrNeocore** [comment] 2021-07-01 14:46
@mayankshriv I don't have that big table available right now, but I'll try it out whenever possible :)

**Comment by MrNeocore** [comment] 2021-07-11 16:15
@mayankshriv I can confirm a degradation in performance when using a large `LIMIT` value without ORDER BY 
Performance remains better than with ORDER BY though. (~250ms vs 350ms)
Interestingly, adding the same `LIMIT` to the query with `ORDER BY` improves performance

**In summary (same context as before):**
- `select DISTINCT(kpi) from kpis` -> less than 10ms
- `select DISTINCT(kpi) from kpis LIMIT 1000000` -> ~250 ms
- `select DISTINCT(kpi) from kpis ORDER BY kpi ` -> ~350ms
- `select DISTINCT(kpi) from kpis ORDER BY kpi LIMIT 1000000` -> ~250 ms

**Comment by atris** [comment] 2021-07-12 04:59
@MrNeocore Not surprised. In the first case, we are still early terminating although with a larger limit as compared to the previous iteration. It is faster than ORDER BY query due to the explanation above.

Should we close this ticket as expected behaviour?

**Comment by MrNeocore** [comment] 2021-07-12 09:01
This issue is not impacting my use cases much at all, but should "technically understandable" be considered "expected behavior" (from a user perspective) ?

Of course if it seems there's no way to improve / fix the issue, then let's close it, as "known behavior" maybe ?

Maybe I'm just being pedantic lol

**Comment by atris** [comment] 2021-07-12 09:04
I would say that we document this behaviour and make users aware of this scenario. WDYT?

**Comment by mayankshriv** [comment] 2021-07-19 23:48
Since we have agreement, marking the issue as closed.

**Closed** 2021-07-19 23:49 UTC
