### ISSUE TITLE
Kafka ingestion by plugin not picking up latest messages with auto.offset.reset=smallest

### ISSUE THREAD

**Issue by dongxiaoman** [apache/incubator-pinot#5955] opened 2020-09-01 17:50 UTC
Currently we are running secure Kafka (2.0+) and TLS connection; Kafka streaming was done by creating our own plugin to do transformation.

The bug happens when we specify `"stream.kafka.consumer.prop.auto.offset.reset": "smallest"` property in a Pinot realtime table. The pinot server will process all the data in Kafka, and then stops sending Kafka messages to our plugin.

If we specify `"latest"`, Pinot controller throws some error while fails to provide original exception ""Failed to fetch the offset for topic:" in "PinotLLCRealtimeSegmentManager.java" file.

The only way it works is to delete that property, and streaming works.

We are using 0.5.0 development snapshot (roughly 08-13-2020)

**Comment by dongxiaoman** [comment] 2020-09-01 18:07
Error Log when set property to `latest`: (sorry for the bad format)
```
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853256] 2020/09/01 17:09:46.852 ERROR [PinotTableRestletResource] [grizzly-http-server-5] Failed to fetch the offset for topic: ledger.v2, partition: 0 with criteria: OffsetCriteria{_off$
etType=CUSTOM, _offsetString='latest'}
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853299] java.lang.IllegalStateException: Failed to fetch the offset for topic: ledger.v2, partition: 0 with criteria: OffsetCriteria{_offsetType=CUSTOM, _offsetString='latest'}
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853351]        at org.apache.pinot.controller.helix.core.realtime.PinotLLCRealtimeSegmentManager.getPartitionOffset(PinotLLCRealtimeSegmentManager.java:612) ~[pinot-all-0.5.0-2020-08-13-$
NAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853392]        at org.apache.pinot.controller.helix.core.realtime.PinotLLCRealtimeSegmentManager.setupNewPartition(PinotLLCRealtimeSegmentManager.java:1012) ~[pinot-all-0.5.0-2020-08-13-$
NAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853430]        at org.apache.pinot.controller.helix.core.realtime.PinotLLCRealtimeSegmentManager.setUpNewTable(PinotLLCRealtimeSegmentManager.java:226) ~[pinot-all-0.5.0-2020-08-13-SNAPS$
OT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853479]        at org.apache.pinot.controller.helix.core.PinotTableIdealStateBuilder.buildLowLevelRealtimeIdealStateFor(PinotTableIdealStateBuilder.java:114) ~[pinot-all-0.5.0-2020-08-13$
SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853516]        at org.apache.pinot.controller.helix.core.PinotHelixResourceManager.ensureRealtimeClusterIsSetUp(PinotHelixResourceManager.java:1284) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT$
jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853552]        at org.apache.pinot.controller.helix.core.PinotHelixResourceManager.addTable(PinotHelixResourceManager.java:1139) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependenci$
s.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853582]        at org.apache.pinot.controller.api.resources.PinotTableRestletResource.addTable(PinotTableRestletResource.java:128) ~[pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependenc
ies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853600]        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853623]        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853644]        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853655]        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853678]        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[pinot-all-0.5.0-2020-
08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853699]        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) [pinot-all-0.5.0-2020-08-13-SNAPSHOT
-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853751]        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) [pinot-all-0.5.0-2020-08-13-SNAPSHO
T-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853789]        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) [pinot-all-0.5.0
-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853820]        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) [pinot-all-0.5.0-2020-08-13-SNAPSH
OT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853850]        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-
08-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853877]        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-0
8-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853897]        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08
-13-SNAPSHOT-5ac67eb1a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853929]        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1
a1210cb6c0c76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853950]        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c
76d81d138cac29d0d3d4e]
@^ r=ledger a=unilog-host $@[2020-09-01 17:09:46.853970]        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [pinot-all-0.5.0-2020-08-13-SNAPSHOT-jar-with-dependencies.jar:0.5.0-2020-08-13-SNAPSHOT-5ac67eb1a1210cb6c0c
76d81d138cac29d0d3d4e
```

**Comment by dongxiaoman** [comment] 2020-09-01 18:08
There is no error log when set to "smallest". We ingested exactly 5000 messages for that real time table, which is a bit strange. I don't think Kafka retention has something to do with that.

**Comment by dongxiaoman** [comment] 2020-09-01 18:42
o reproduce the issue, we need to start from a clean slate. I can reproduce after deleting the table completely and start fresh. below are the steps
delete the old table
set "stream.kafka.consumer.prop.auto.offset.reset": "smallest" , table created, got exactly 50000 documents and stopped
delete table again
change value in config to earliest or latest, cannot create realtime table with the error OffsetCriteria{_offsetType=CUSTOM, _offsetString='earliest'}
the value largest or smallest works. in our config we are using "stream.kafka.consumer.factory.class.name": "org.apache.pinot.plugin.stream.kafka20.KafkaConsumerFactory".
Item #2 is still an issue, where we can only see 50000 documents in pinotcontroller UI (query console)

**Comment by dongxiaoman** [comment] 2020-09-01 18:48
I think the major issue here is that with "smallest" the new Kafka messages are not picked up at some point.

**Comment by dongxiaoman** [comment] 2020-09-01 20:02
Switched to a new table, seeing flow of below warning:
```
WARN [LLRealtimeSegmentDataManager_finance_edges_v2_temp__57__0__20200901T1957Z] [finance_edges_v2_temp__33__0__20200901T1957Z] CommitEnd failed with response {"streamPartitionMsgOffset":null,"buildTimeSec":-1,"isSplitCommitType":false,"status":"FAILED","offset":-1}
```

**Comment by Jackie-Jiang** [comment] 2020-09-01 22:20
After some investigation, the problem is on the deep storage side instead of the Kafka ingestion. Close this issue now.

**Closed by Jackie-Jiang** 2020-09-01 22:20 UTC
